"project_id_env": "CROWDIN_PROJECT_ID"
"api_token_env": "CROWDIN_PERSONAL_TOKEN"
"base_path": "."
"base_url": "https://api.crowdin.com"

"preserve_hierarchy": true

files: [
  {
    "source": "src/config/i18n/defaults.json",
    "translation": "src/config/i18n/%two_letters_code%/resource.json",
  }
]