project_id: "934103"
base_path: "."
preserve_hierarchy: true

files:
  - source: src/config/i18n/defaults.json
    translation: src/config/i18n/%two_letters_code%/resource.json
    languages_mapping:
      two_letters_code:
        pt-BR: pt-br
