name: Build

on: [push]

jobs:
  tests:
    name: "Tests"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: install, build, and test
      run: |
        yarn install
        yarn run build
        yarn test
      env:
        CI: true
  coverage:
    name: "Coverage"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 18.x
      uses: actions/setup-node@v1
      with:
        node-version: '18.x'
    - name: install and coverage
      run: |
        yarn install
        yarn test --coverage
      env:
        CI: true
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1.0.2
      with:
        token: ${{secrets.CODECOV_TOKEN}}
        file: src/coverage/lcov.info
